name: Build and Release Front End
run-name: "Building ${{ github.workflow }}-${{ github.ref_name }}"

on:
  workflow_dispatch:

  push:
    paths:
      - 'frontend/**'
    branches:
      - main

# Kill previous builds that are currently running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # AWS region to deploy to
  AWS_REGION: "us-east-1"

  # Node version used to build the product (See https://angular.io/guide/versions for correct version)
  NODE_VERSION: "20"

permissions:
  id-token: write # This is required for requesting the JWT from AWS
  contents: read  # This is required for actions/checkout
  packages: read  # This is required to read private repositories

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch code from git
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      # Authenticate with AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_NUMBER }}:role/${{ vars.AWS_GITHUB_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      # Download and install the Node version used to build
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com
          cache: npm # Cache dependencies so future builds run quicker

      # Install dependencies
      - name: Install Node Dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Run the build
      - name: Run Build
        run: npm run build -w frontend

      # Deploy
      - name: Deploy to S3
        run: |
          cd frontend/dist/portfolio/browser
          aws s3 sync --quiet --delete --exclude "index.html" . s3://jf-portfolio-web
          aws s3 cp index.html s3://jf-portfolio-web/index.html \
            --cache-control "max-age=0,no-cache,no-store,must-revalidate"

      # Invalidate the CDN cache for the index
      - name: Invalidate CDN Cache
        run: aws cloudfront create-invalidation --distribution-id E1E52SK17Y9LID --paths "/*"
